# Generated by Django 3.2.8 on 2021-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('1', 'Productos de consumo básico'), ('2', 'Productos de impulso'), ('3', 'Productos de urgencia')], default='1', max_length=20)),
                ('estado', models.CharField(choices=[('1', 'Disponible'), ('2', 'Reservado'), ('3', 'Agotado')], default='1', max_length=20)),
                ('imagen', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
